jaffle_shop:
  target: dev
  outputs:
    dev:
      password: root
      port: 3306
      schema: test
      server: 192.168.41.64
      type: mariadb
      username: root
      ssl_disabled: True
#    prod:
#      database:
#      - schema
#      driver: MySQL ODBC 8.0 ANSI Driver
#      password:
#      - password
#      port:
#      - port
#      schema:
#      - schema
#      server:
#      - 192.168.13.16
#      type: mariadb
#      username:
#      - username
#  target: dev
taxi_ride_ny:
  outputs:
    dev:
      dataset: dbt
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /home/ubuntu/zoomcamp/04-analytic-enginnering/service-account-gcp.json
      location: asia-southeast2
      method: service-account
      priority: interactive
      project: graphite-scout-414507
      threads: 4
      type: bigquery
  target: dev
#taxi_rides_ny:
#  outputs:
#    dev:
#      dataset: dbt
#      job_execution_timeout_seconds: 300
#      job_retries: 1
#      keyfile: /home/ubuntu/de_zoomcamp/04-analytic-engineering/service-account-gcp.json
#      location: US
#      method: service-account
#      priority: interactive
#      project: graphite-scout-414507
#      threads: 4
#      type: bigquery
#  target: dev
